# argo-rollouts-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: default
roleRef:
  kind: Role
  name: argo-rollouts-role
  apiGroup: rbac.authorization.k8s.io

